FROM alpine:latest
LABEL maintainer="roy@nisra.net"

RUN apk update && \
	apk add libc-dev ucspi-tcp gcc make && \
	rm -rf /var/cache/apk/*

# create ctf-user
RUN adduser -u 1337 -D -s /bin/bash -h /home/ctf ctf
WORKDIR /home/ctf/

COPY ./src .

# Perm
RUN chmod 775 /home/ctf/*.sh

USER ctf

# Set problem env var
ENV PROB=lab1

CMD ["/home/ctf/entry.sh"]