FROM ubuntu:18.04
MAINTAINER roy4801

RUN dpkg --add-architecture i386
RUN apt-get update --fix-missing && apt-get -y upgrade
RUN apt-get install -y libc6:i386 libstdc++6:i386
RUN apt-get install xinetd -y

RUN useradd -m ctf
RUN chmod 774 /tmp
RUN chmod -R 774 /var/tmp
RUN chmod -R 774 /dev
RUN chmod -R 774 /run
RUN chmod 1733 /tmp /var/tmp /dev/shm
RUN chown -R root:root /home/ctf

CMD ["/usr/sbin/xinetd","-dontfork"]