FROM php:5-apache
LABEL maintainer="theo@nisra.net"
COPY index.php /var/www/html/
COPY init.sql README.txt setup.sh /
WORKDIR /var/www/html
RUN chmod +x /setup.sh && \
    usermod -G www-data root && \
    mkdir /var/www/html/sandbox && \
    chown -R www-data:www-data /var/www/html/ && \
    apt-get update && \
    apt-get install mysql-server -y && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 80
CMD ["/setup.sh"]