FROM php:7-apache
LABEL maintainer="theo@nisra.net"
COPY src /var/www/html
COPY README.txt /README.txt
WORKDIR /var/www/html
RUN mkdir /var/www/html/sandbox && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R 770 /var/www/html/sandbox && \
    usermod -G www-data root
EXPOSE 80