#!/bin/bash
PROB=bof_2

echo $ARGS

if [[ "$1" == "s" || "$1" == "stop" ]]; then
	echo Killing the containers...
	docker kill pwn_test
	docker kill $PROB
	echo Completed
elif [[ "$1" == "u" ||  "$1" == "up" ]]; then
	docker build . -t roy4801/${PROB}
	docker run -p 8888:1337 -d --name ${PROB} --rm --privileged roy4801/${PROB}
elif [[ "$1" == "t" ||  "$1" == "test" ]]; then
	docker build . -t roy4801/${PROB}
	docker run -p 8888:1337 -it --name pwn_test --rm --privileged roy4801/${PROB} $2
elif [[ "$1" == "sh" ||  "$1" == "shell" ]]; then
	docker build . -t roy4801/${PROB}
	docker run -p 8888:1337 -it --name pwn_test --rm --privileged roy4801/${PROB} /bin/bash
else
	echo "Usage: $0 [stop|up|test|shell]"
fi