FROM php:7-apache
LABEL maintainer="theo@nisra.net"
COPY *.php *.txt /var/www/html/
WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www/html/ && \
    apt-get update && \ 
    apt-get install iputils-ping -y && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 80