FROM php:7-apache
LABEL maintainer="theo@nisra.net"
COPY *.php /var/www/html
COPY README.txt /README.txt
WORKDIR /var/www/html
RUN mkdir /var/www/html/upload && \
    chown -R www-data:www-data /var/www/html/ && \
    usermod -G www-data root
EXPOSE 80